SELECT 
    TRUNC(NVL(BVSP_BPA.BPA_VALOR1 - BVSP_BPP.BPP_VALOR1,0),2) AS CCL
FROM BVSP_BPP
INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
WHERE BVSP_BPP.ID_EMPRESA = 65
AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
AND ROWNUM < 2;