SELECT 
     NVL(TRUNC((BPP1.BPP_VALOR1/(BPP1.BPP_VALOR1+BPP2.BPP_VALOR1) * 100),2),0) AS CE
FROM BVSP_BPP
INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
WHERE BVSP_BPP.ID_EMPRESA = 65
AND BPP1.BPP_CONTA_CONTABIL = '2.01'
AND BPP2.BPP_CONTA_CONTABIL = '2.02'
AND ROWNUM < 2;
