SELECT
    (SELECT 
      TRUNC(NVL((((BPP.BPP_VALOR1/(DRE.DRE_VALOR1 * -1)) + (BPA.BPA_VALOR1 - BPA.BPA_VALOR2)) * 360),0),2) AS PMP
    FROM BVSP_DRE DRE
    INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
    INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
    WHERE DRE.ID_EMPRESA = 65
    AND DRE.DRE_CONTA_CONTABIL = '3.02'
    AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
    AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
    AND ROWNUM < 2)
    -
    ((SELECT 
        TRUNC(NVL(((BPA.BPA_VALOR1/(DRE.DRE_VALOR1 * -1)) * 360),0),2) AS PME
      FROM BVSP_DRE DRE
      INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
      WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
      AND DRE.DRE_CONTA_CONTABIL = '3.02'
      AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
      AND ROWNUM < 2)
      +
      (SELECT 
        TRUNC(NVL(((BPA.BPA_VALOR1/DRE.DRE_VALOR1) * 360),0),2) AS PMR
      FROM BVSP_DRE DRE
      INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
      WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
      AND DRE.DRE_CONTA_CONTABIL = '3.01'
      AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
      AND ROWNUM < 2)
    ) AS CF
FROM BVSP_DRE
WHERE BVSP_DRE.ID_EMPRESA = 65
AND ROWNUM < 2;