SELECT 
    TRUNC(NVL(DRE.DRE_VALOR1/BPA.BPA_VALOR1,0),2) AS GA
FROM BVSP_DRE DRE
INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE DRE.ID_EMPRESA = 65
AND DRE.DRE_CONTA_CONTABIL = '3.01'
AND BPA.BPA_CONTA_CONTABIL = '1'
AND ROWNUM < 2;