SELECT 
     NVL(TRUNC((((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) /BPP1.BPP_VALOR1) * 100),2),0)  AS IPL
FROM BVSP_BPA
INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE BVSP_BPA.ID_EMPRESA = 65
AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
AND BPP1.BPP_CONTA_CONTABIL = '2.03'
AND ROWNUM < 2;
