SELECT 
    TRUNC(NVL(BVSP_BPA.BPA_VALOR1 / BVSP_BPP.BPP_VALOR1,0),2) AS LC
FROM BVSP_BPA
INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE BVSP_BPP.ID_EMPRESA = 65
AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
AND ROWNUM < 2;