SELECT 
   TRUNC(NVL(((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) / BPP1.BPP_VALOR1),0),2) AS LS
FROM BVSP_BPA
INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE BVSP_BPA.ID_EMPRESA = 65
AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
AND BPP1.BPP_CONTA_CONTABIL = '2.01'
AND ROWNUM < 2;