SELECT 
  TRUNC(NVL(((DRE.DRE_VALOR1/DRE1.DRE_VALOR1) * 100),0),2) AS ML
FROM BVSP_DRE DRE
INNER JOIN BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
WHERE DRE.ID_EMPRESA = 65
AND DRE.DRE_CONTA_CONTABIL = '3.09'
AND DRE1.DRE_CONTA_CONTABIL = '3.01'
AND ROWNUM < 2;