SELECT 
      NVL(TRUNC((((BPP2.BPP_VALOR1 + BPP3.BPP_VALOR1) / BPP4.BPP_VALOR1) * 100),2),2) AS PCT
FROM BVSP_BPP BPP1
INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
INNER JOIN BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
INNER JOIN BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
WHERE BPP1.ID_EMPRESA = 65
AND BPP2.BPP_CONTA_CONTABIL = '2.01'
AND BPP3.BPP_CONTA_CONTABIL = '2.02'
AND BPP4.BPP_CONTA_CONTABIL = '2.03'
AND ROWNUM < 2;