USE `dbinvistaja`;
DROP procedure IF EXISTS `BVSP_SP_INDICADORES`;

DELIMITER $$
USE `dbinvistaja`$$
CREATE PROCEDURE `BVSP_SP_INDICADORES` (
	IN vID_EMPRESA INT,
    IN vANO1 VARCHAR(4),
    IN vANO2 VARCHAR(4),
    IN vANO3 VARCHAR(4)
)
BEGIN
	DECLARE vCCL REAL DEFAULT 0;
	DECLARE vCE REAL DEFAULT 0;
	DECLARE vCF REAL DEFAULT 0;
	DECLARE vCO REAL DEFAULT 0;
	DECLARE vGA REAL DEFAULT 0;
	DECLARE vIPL REAL DEFAULT 0;
	DECLARE vLC REAL DEFAULT 0;
	DECLARE vLG REAL DEFAULT 0;
	DECLARE vLS REAL DEFAULT 0;
	DECLARE vML REAL DEFAULT 0;
	DECLARE vPCT REAL DEFAULT 0;
	DECLARE vPME REAL DEFAULT 0;
	DECLARE vPMP REAL DEFAULT 0;
	DECLARE vPMR REAL DEFAULT 0;
	DECLARE vRA REAL DEFAULT 0;
	DECLARE vRPL REAL DEFAULT 0;
  
	DELETE FROM BVSP_INDICADORES 
WHERE
    BVSP_INDICADORES.ID_EMPRESA = vID_EMPRESA;
        
	#########ANO 1#########
	
	##CCL:
	SET vCCL = (SELECT 
		 ROUND(IFNULL(BVSP_BPA.BPA_VALOR1 - BVSP_BPP.BPP_VALOR1,0),2) AS CCL
	FROM BVSP_BPP
	INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
	AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
	LIMIT 1);
	
	##CE:
	SET vCE = (SELECT 
		 IFNULL(ROUND((BPP1.BPP_VALOR1/
		 (CASE (BPP1.BPP_VALOR1+BPP2.BPP_VALOR1) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR1+BPP2.BPP_VALOR1) END)
		 * 100),2),0) AS CE 
	FROM BVSP_BPP
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BPP1.BPP_CONTA_CONTABIL = '2.01'
	AND BPP2.BPP_CONTA_CONTABIL = '2.02'
	LIMIT 1);  
	
	##CF:
	SET vCF = (SELECT
		(SELECT 
		  ROUND(IFNULL(((BPP.BPP_VALOR1/
		  ((CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END) 
		   + (BPA.BPA_VALOR1 - 0))) * 360),0),2) AS PMP
		FROM BVSP_DRE DRE
		INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
		WHERE DRE.ID_EMPRESA = vID_EMPRESA
		AND DRE.DRE_CONTA_CONTABIL = '3.02'
		AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
		LIMIT 1)
		-
		((SELECT 
			ROUND(IFNULL(((BPA.BPA_VALOR1/
			(CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
			) * 360),0),2) AS PME
		  FROM BVSP_DRE DRE
		  INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		  WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
		  AND DRE.DRE_CONTA_CONTABIL = '3.02'
		  AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		  LIMIT 1)
		  +
		  (SELECT 
			ROUND(IFNULL(((BPA.BPA_VALOR1/
			(CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
			) * 360),0),2) AS PMR
		  FROM BVSP_DRE DRE
		  INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		  WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
		  AND DRE.DRE_CONTA_CONTABIL = '3.01'
		  AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
		  LIMIT 1)
		) AS CF
	FROM BVSP_DRE
	WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
	LIMIT 1);
	
	##CO:
	SET vCO =(SELECT
		ROUND(IFNULL(
		(SELECT 
		  ROUND(IFNULL(((BPA.BPA_VALOR1/
		  (CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
		  ) * 360),0),2)
		FROM BVSP_DRE DRE
		INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		WHERE DRE.ID_EMPRESA = vID_EMPRESA
		AND DRE.DRE_CONTA_CONTABIL = '3.02'
		AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		LIMIT 1)
	  +
		(SELECT 
		  ROUND(IFNULL(((BPA.BPA_VALOR1/
		  (CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
		  ) * 360),0),2)
		FROM BVSP_DRE DRE
		INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		WHERE DRE.ID_EMPRESA = vID_EMPRESA
		AND DRE.DRE_CONTA_CONTABIL = '3.01'
		AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
		LIMIT 1)
		,0),2) AS CO 
	FROM BVSP_DRE
	WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
	LIMIT 1);
	
	
	##GA:
	SET vGA = (SELECT 
		ROUND(IFNULL(DRE.DRE_VALOR1/
		(CASE BPA.BPA_VALOR1 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR2 END) 
		,0),2) AS GA 
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.01'
	AND BPA.BPA_CONTA_CONTABIL = '1'
	LIMIT 1);
	
	##IPL:
	SET vIPL = (SELECT 
		 IFNULL(ROUND((((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) /
		 (CASE BPP1.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR1 END)
		 ) * 100),2),0)  AS IPL
	FROM BVSP_BPA
	INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
	AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
	AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
	AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
	AND BPP1.BPP_CONTA_CONTABIL = '2.03'
	LIMIT 1);
	
	##LC:
	SET vLC = (SELECT 
		ROUND(IFNULL(BVSP_BPA.BPA_VALOR1 / 
		(CASE BVSP_BPP.BPP_VALOR1 WHEN 0 THEN 1 ELSE BVSP_BPP.BPP_VALOR1 END)
		,0),2) AS LC
	FROM BVSP_BPA
	INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
	AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
	LIMIT 1);

	##LG:
	SET vLG =(SELECT
		ROUND(IFNULL(BPA.BPA_VALOR1/
		(CASE (BPP1.BPP_VALOR1 + BPP2.BPP_VALOR1) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR1 + BPP2.BPP_VALOR1) END)
		,0),2) AS LG
	FROM BVSP_BPA BPA
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
	WHERE BPA.ID_EMPRESA = vID_EMPRESA
	AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
	AND BPP1.BPP_CONTA_CONTABIL = '2.01'
	AND BPP2.BPP_CONTA_CONTABIL = '2.02'
	LIMIT 1);
	
	##LS:
	SET vLS = (SELECT 
	   ROUND(IFNULL(((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) / 
	   (CASE BPP1.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR1 END)
	   ),0),2) AS LS
	FROM BVSP_BPA
	INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
	AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
	AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
	AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
	AND BPP1.BPP_CONTA_CONTABIL = '2.01'
	LIMIT 1);
  
	##ML:
	SET vML = (SELECT 
	  ROUND(IFNULL(((DRE.DRE_VALOR1/
	  (CASE DRE1.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE1.DRE_VALOR1 END)
	  ) * 100),0),2) AS ML
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.09'
	AND DRE1.DRE_CONTA_CONTABIL = '3.01'
	LIMIT 1);
	
	##PCT:
	SET vPCT = (SELECT 
		  IFNULL(ROUND((((BPP2.BPP_VALOR1 + BPP3.BPP_VALOR1) / 
		  (CASE BPP4.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP4.BPP_VALOR1 END)
		  ) * 100),2),2) AS PCT
	FROM BVSP_BPP BPP1
	INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
	WHERE BPP1.ID_EMPRESA = vID_EMPRESA
	AND BPP2.BPP_CONTA_CONTABIL = '2.01'
	AND BPP3.BPP_CONTA_CONTABIL = '2.02'
	AND BPP4.BPP_CONTA_CONTABIL = '2.03'
	LIMIT 1);
	
	##PME:
	SET vPME = (SELECT 
	  ROUND(IFNULL(((BPA.BPA_VALOR1/
	  (CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
	  ) * 360),0),2) AS PME
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.02'
	AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
	LIMIT 1);
	
	##PMP:
	 SET vPMP = (SELECT 
	  ROUND(IFNULL(((BPP.BPP_VALOR1/
	  ((CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
	   + (BPA.BPA_VALOR1 - 0))) * 360),0),2) AS PMP 
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.02'
	AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
	AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
	LIMIT 1);
	
	##PMR:
	SET vPMR = (SELECT 
	  ROUND(IFNULL(((BPA.BPA_VALOR1/
	  (CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
	  ) * 360),0),2) AS PMR
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.01'
	AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
	LIMIT 1);
	
	##RA:
	SET vRA = (SELECT 
	  ROUND(IFNULL((DRE.DRE_VALOR1/
	  (CASE BPA.BPA_VALOR1 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR1 END)
	  ) * 100,0),2) AS RA
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.09'
	AND BPA.BPA_CONTA_CONTABIL = '1'
	LIMIT 1);
	
	##RPL:
	SET vRPL = (SELECT 
	  ROUND(IFNULL((DRE.DRE_VALOR1/
	  (CASE BPP.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP.BPP_VALOR1 END)
	  ) * 100,0),2) AS RPL
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.09'
	AND BPP.BPP_CONTA_CONTABIL = '2.03'
	LIMIT 1);
	
	
	##INSERE DADOS CALCULADOS NA TABELA:
	INSERT INTO BVSP_INDICADORES 
		  (ID_EMPRESA,
		   ANO,
		   IE_PCT,
		   IE_CE,
		   IE_IPL,
		   IL_LG,
		   IL_LC,
		   IL_LS,
		   IL_CCL,
		   IR_GA,
		   IR_ML,
		   IR_RA,
		   IR_RPL,
		   IA_PME,
		   IA_PMR,
		   IA_PMP,
		   IA_CO,
		   IA_CF) 
	 VALUES 
		  (vID_EMPRESA,
		   vANO1,
		   vPCT,
		   vCE,
		   vIPL,
		   vLG,
		   vLC,
		   vLS,
		   vCCL,
		   vGA,
		   vML,
		   vRA,
		   vRPL,
		   vPME,
		   vPMR,
		   vPMP,
		   vCO,
		   vCF);
		   
		   
		   
	#########ANO 2#########
	##CCL:
	SET vCCL = (SELECT 
		ROUND(IFNULL(BVSP_BPA.BPA_VALOR2 - BVSP_BPP.BPP_VALOR2,0),2) AS CCL 
	FROM BVSP_BPP
	INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
	AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
	LIMIT 1);
	
	##CE:
	SET vCE = (SELECT 
		 IFNULL(ROUND((BPP1.BPP_VALOR2/
		 (CASE (BPP1.BPP_VALOR2+BPP2.BPP_VALOR2) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR2+BPP2.BPP_VALOR2) END)
		 * 100),2),0) AS CE  
	FROM BVSP_BPP
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BPP1.BPP_CONTA_CONTABIL = '2.01'
	AND BPP2.BPP_CONTA_CONTABIL = '2.02'
	LIMIT 1);   
	
	##CF:
	SET vCF =(SELECT
		 (SELECT 
			ROUND(IFNULL(((BPP.BPP_VALOR2/
			((CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
			 + (BPA.BPA_VALOR2 - BPA.BPA_VALOR1))) * 360),0),2) AS PMP 
		  FROM BVSP_DRE DRE
		  INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		  INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
		  WHERE DRE.ID_EMPRESA = vID_EMPRESA
		  AND DRE.DRE_CONTA_CONTABIL = '3.02'
		  AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		  AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
		  LIMIT 1)
		
		-
		((SELECT 
			ROUND(IFNULL(((BPA.BPA_VALOR2/
			(CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
			) * 360),0),2) AS PME
		  FROM BVSP_DRE DRE
		  INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		  WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
		  AND DRE.DRE_CONTA_CONTABIL = '3.02'
		  AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		  LIMIT 1)
		  +
		  (SELECT 
			ROUND(IFNULL(((BPA.BPA_VALOR2/
			(CASE DRE.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR2 END)
			) * 360),0),2) AS PMR
		  FROM BVSP_DRE DRE
		  INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		  WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
		  AND DRE.DRE_CONTA_CONTABIL = '3.01'
		  AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
		  LIMIT 1)
		) AS CF
	FROM BVSP_DRE
	WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
	LIMIT 1);
	
	##CO:
	SET vCO =(SELECT
		 ROUND(IFNULL(
		(SELECT 
		  ROUND(IFNULL(((BPA.BPA_VALOR2/
		  (CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
		  ) * 360),0),2)
		FROM BVSP_DRE DRE
		INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		WHERE DRE.ID_EMPRESA = vID_EMPRESA
		AND DRE.DRE_CONTA_CONTABIL = '3.02'
		AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
		LIMIT 1)
	  +
		(SELECT 
		  ROUND(IFNULL(((BPA.BPA_VALOR2/
		  (CASE DRE.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR2 END)
		  ) * 360),0),2)
		FROM BVSP_DRE DRE
		INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
		WHERE DRE.ID_EMPRESA = vID_EMPRESA
		AND DRE.DRE_CONTA_CONTABIL = '3.01'
		AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
		LIMIT 1)
		,0),2) AS CO 
	FROM BVSP_DRE
	WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
	LIMIT 1);
	
	
	##GA:
	SET vGA =(SELECT 
		ROUND(IFNULL(DRE.DRE_VALOR2/
		(CASE BPA.BPA_VALOR2 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR2 END) 
		,0),2) AS GA 
	FROM BVSP_DRE DRE
	INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
	WHERE DRE.ID_EMPRESA = vID_EMPRESA
	AND DRE.DRE_CONTA_CONTABIL = '3.01'
	AND BPA.BPA_CONTA_CONTABIL = '1'
	LIMIT 1);
	
	##IPL:
	SET vIPL = (SELECT 
		 IFNULL(ROUND((((BPA1.BPA_VALOR2 + BPA2.BPA_VALOR2 + BPA3.BPA_VALOR2) /
		 (CASE BPP1.BPP_VALOR2 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR2 END)
		 ) * 100),2),0)  AS IPL 
	FROM BVSP_BPA
	INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
	AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
	AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
	AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
	AND BPP1.BPP_CONTA_CONTABIL = '2.03'
	LIMIT 1);
	
	##LC:
	SET vLC = (SELECT 
		ROUND(IFNULL(BVSP_BPA.BPA_VALOR2 / 
		(CASE BVSP_BPP.BPP_VALOR2 WHEN 0 THEN 1 ELSE BVSP_BPP.BPP_VALOR2 END)
		,0),2) AS LC
	FROM BVSP_BPA
	INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
	WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
	AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
	AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
	LIMIT 1);

	SET vLG = (SELECT 
		ROUND(IFNULL(BPA.BPA_VALOR2 / (CASE (BPP1.BPP_VALOR2 + BPP2.BPP_VALOR2)
                        WHEN 0 THEN 1
                        ELSE (BPP1.BPP_VALOR2 + BPP2.BPP_VALOR2)
                    END),
                    0),
            2) AS LG
FROM
    BVSP_BPA BPA
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
WHERE
    BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
LIMIT 1);
	
	SET vLS = (SELECT 
		ROUND(IFNULL(((BPA1.BPA_VALOR2 + BPA2.BPA_VALOR2 + BPA3.BPA_VALOR2) / (CASE BPP1.BPP_VALOR2
                        WHEN 0 THEN 1
                        ELSE BPP1.BPP_VALOR2
                    END)),
                    0),
            2) AS LS
FROM
    BVSP_BPA
        INNER JOIN
    BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE
    BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
        AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
        AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
LIMIT 1);
  
	SET vML = (SELECT 
		ROUND(IFNULL(((DRE.DRE_VALOR2 / (CASE DRE1.DRE_VALOR2
                        WHEN 0 THEN 1
                        ELSE DRE1.DRE_VALOR2
                    END)) * 100),
                    0),
            2) AS ML
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND DRE1.DRE_CONTA_CONTABIL = '3.01'
LIMIT 1);
	
	SET vPCT = (SELECT 
		IFNULL(ROUND((((BPP2.BPP_VALOR2 + BPP3.BPP_VALOR2) / (CASE BPP4.BPP_VALOR2
                        WHEN 0 THEN 1
                        ELSE BPP4.BPP_VALOR2
                    END)) * 100),
                    2),
            2) AS PCT
FROM
    BVSP_BPP BPP1
        INNER JOIN
    BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
WHERE
    BPP1.ID_EMPRESA = vID_EMPRESA
        AND BPP2.BPP_CONTA_CONTABIL = '2.01'
        AND BPP3.BPP_CONTA_CONTABIL = '2.02'
        AND BPP4.BPP_CONTA_CONTABIL = '2.03'
LIMIT 1);
	
	SET vPME = (SELECT 
		ROUND(IFNULL(((BPA.BPA_VALOR2 / (CASE (DRE.DRE_VALOR2 * - 1)
                        WHEN 0 THEN 1
                        ELSE (DRE.DRE_VALOR2 * - 1)
                    END)) * 360),
                    0),
            2) AS PME
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
LIMIT 1);
	
	SET vPMP = (SELECT 
		ROUND(IFNULL(((BPP.BPP_VALOR2 / ((CASE (DRE.DRE_VALOR2 * - 1)
                        WHEN 0 THEN 1
                        ELSE (DRE.DRE_VALOR2 * - 1)
                    END) + (BPA.BPA_VALOR2 - BPA.BPA_VALOR1))) * 360),
                    0),
            2) AS PMP
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
LIMIT 1);
	
	SET vPMP = (SELECT 
		ROUND(IFNULL(((BPP.BPP_VALOR2 / ((CASE (DRE.DRE_VALOR2 * - 1)
                        WHEN 0 THEN 1
                        ELSE (DRE.DRE_VALOR2 * - 1)
                    END) + (BPA.BPA_VALOR2 - BPA.BPA_VALOR3))) * 360),
                    0),
            2) AS PMP
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
LIMIT 1);
	
	SET vPMR = (SELECT 
		ROUND(IFNULL(((BPA.BPA_VALOR2 / (CASE DRE.DRE_VALOR2
                        WHEN 0 THEN 1
                        ELSE DRE.DRE_VALOR2
                    END)) * 360),
                    0),
            2) AS PMR
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
LIMIT 1);
	
	SET vRA = (SELECT 
    ROUND(IFNULL((DRE.DRE_VALOR2 / (CASE BPA.BPA_VALOR2
                        WHEN 0 THEN 1
                        ELSE BPA.BPA_VALOR2
                    END)) * 100,
                    0),
            2) AS RA
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPA.BPA_CONTA_CONTABIL = '1'
LIMIT 1);
	
	SET vRPL = (SELECT 
		ROUND(IFNULL((DRE.DRE_VALOR2 / (CASE BPP.BPP_VALOR2
                        WHEN 0 THEN 1
                        ELSE BPP.BPP_VALOR2
                    END)) * 100,
                    0),
            2) AS RPL
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPP.BPP_CONTA_CONTABIL = '2.03'
LIMIT 1);
	
	
	##INSERE DADOS CALCULADOS NA TABELA:
	INSERT INTO BVSP_INDICADORES 
		  (ID_EMPRESA,
		   ANO,
		   IE_PCT,
		   IE_CE,
		   IE_IPL,
		   IL_LG,
		   IL_LC,
		   IL_LS,
		   IL_CCL,
		   IR_GA,
		   IR_ML,
		   IR_RA,
		   IR_RPL,
		   IA_PME,
		   IA_PMR,
		   IA_PMP,
		   IA_CO,
		   IA_CF) 
	 VALUES 
		  (vID_EMPRESA,
		   vANO2,
		   vPCT,
		   vCE,
		   vIPL,
		   vLG,
		   vLC,
		   vLS,
		   vCCL,
		   vGA,
		   vML,
		   vRA,
		   vRPL,
		   vPME,
		   vPMR,
		   vPMP,
		   vCO,
		   vCF);
		   
		   
SET vCCL = (SELECT 
    ROUND(IFNULL(BVSP_BPA.BPA_VALOR3 - BVSP_BPP.BPP_VALOR3,
                    0),
            2) AS CCL
FROM
    BVSP_BPP
        INNER JOIN
    BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
WHERE
    BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
LIMIT 1);
	
	SET vCE = (SELECT 
     IFNULL(ROUND((BPP1.BPP_VALOR3 / (CASE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3)
                        WHEN 0 THEN 1
                        ELSE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3)
                    END) * 100),
                    2),
            0) AS CE
FROM
    BVSP_BPP
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
WHERE
    BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
LIMIT 1);
	
	SET vCF =(SELECT 
     (SELECT 
            ROUND(IFNULL(((BPP.BPP_VALOR3 / ((CASE (DRE.DRE_VALOR3 * - 1)
                                    WHEN 0 THEN 1
                                    ELSE (DRE.DRE_VALOR3 * - 1)
                                END) + (BPA.BPA_VALOR3 - BPA.BPA_VALOR2))) * 360),
                                0),
                        2) AS PMP
        FROM
            BVSP_DRE DRE
                INNER JOIN
            BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
                INNER JOIN
            BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE
            DRE.ID_EMPRESA = vID_EMPRESA
                AND DRE.DRE_CONTA_CONTABIL = '3.02'
                AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
                AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
        LIMIT 1) - ((SELECT 
            ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE (DRE.DRE_VALOR3 * - 1)
                                    WHEN 0 THEN 1
                                    ELSE (DRE.DRE_VALOR3 * - 1)
                                END)) * 360),
                                0),
                        2) AS PME
        FROM
            BVSP_DRE DRE
                INNER JOIN
            BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE
            DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
                AND DRE.DRE_CONTA_CONTABIL = '3.02'
                AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        LIMIT 1) + (SELECT 
            ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE DRE.DRE_VALOR3
                                    WHEN 0 THEN 1
                                    ELSE DRE.DRE_VALOR3
                                END)) * 360),
                                0),
                        2) AS PMR
        FROM
            BVSP_DRE DRE
                INNER JOIN
            BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE
            DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
                AND DRE.DRE_CONTA_CONTABIL = '3.01'
                AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
        LIMIT 1)) AS CF
FROM
    BVSP_DRE
WHERE
    BVSP_DRE.ID_EMPRESA = vID_EMPRESA
LIMIT 1);
	
	SET vCO =(SELECT 
     ROUND(IFNULL((SELECT 
                            ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE (DRE.DRE_VALOR3 * - 1)
                                                    WHEN 0 THEN 1
                                                    ELSE (DRE.DRE_VALOR3 * - 1)
                                                END)) * 360),
                                                0),
                                        2)
                        FROM
                            BVSP_DRE DRE
                                INNER JOIN
                            BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
                        WHERE
                            DRE.ID_EMPRESA = vID_EMPRESA
                                AND DRE.DRE_CONTA_CONTABIL = '3.02'
                                AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
                        LIMIT 1) + (SELECT 
                            ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE DRE.DRE_VALOR3
                                                    WHEN 0 THEN 1
                                                    ELSE DRE.DRE_VALOR3
                                                END)) * 360),
                                                0),
                                        2)
                        FROM
                            BVSP_DRE DRE
                                INNER JOIN
                            BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
                        WHERE
                            DRE.ID_EMPRESA = vID_EMPRESA
                                AND DRE.DRE_CONTA_CONTABIL = '3.01'
                                AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
                        LIMIT 1),
                    0),
            2) AS CO
FROM
    BVSP_DRE
WHERE
    BVSP_DRE.ID_EMPRESA = vID_EMPRESA
LIMIT 1);
	
	
	SET vGA =(SELECT 
     ROUND(IFNULL(DRE.DRE_VALOR3 / (CASE BPA.BPA_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPA.BPA_VALOR3
                    END),
                    0),
            2) AS GA
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1'
LIMIT 1);
	
	SET vIPL =(SELECT 
     IFNULL(ROUND((((BPA1.BPA_VALOR3 + BPA2.BPA_VALOR3 + BPA3.BPA_VALOR3) / (CASE BPP1.BPP_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPP1.BPP_VALOR3
                    END)) * 100),
                    2),
            0) AS IPL
FROM
    BVSP_BPA
        INNER JOIN
    BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE
    BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
        AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
        AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
        AND BPP1.BPP_CONTA_CONTABIL = '2.03'
LIMIT 1);
	
	SET vLC =(SELECT 
     ROUND(IFNULL(BVSP_BPA.BPA_VALOR3 / (CASE BVSP_BPP.BPP_VALOR3
                        WHEN 0 THEN 1
                        ELSE BVSP_BPP.BPP_VALOR3
                    END),
                    0),
            2) AS LC
FROM
    BVSP_BPA
        INNER JOIN
    BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE
    BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
LIMIT 1);

	SET vLG =(SELECT 
     ROUND(IFNULL(BPA.BPA_VALOR3 / (CASE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3)
                        WHEN 0 THEN 1
                        ELSE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3)
                    END),
                    0),
            2) AS LG
FROM
    BVSP_BPA BPA
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
WHERE
    BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
LIMIT 1);
	
	SET vLS =(SELECT 
     ROUND(IFNULL(((BPA1.BPA_VALOR3 + BPA2.BPA_VALOR3 + BPA3.BPA_VALOR3) / (CASE BPP1.BPP_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPP1.BPP_VALOR3
                    END)),
                    0),
            2) AS LS
FROM
    BVSP_BPA
        INNER JOIN
    BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
WHERE
    BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
        AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
        AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
LIMIT 1);
  
	SET vML =(SELECT 
     ROUND(IFNULL(((DRE.DRE_VALOR3 / (CASE DRE1.DRE_VALOR3
                        WHEN 0 THEN 1
                        ELSE DRE1.DRE_VALOR3
                    END)) * 100),
                    0),
            2) AS ML
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND DRE1.DRE_CONTA_CONTABIL = '3.01'
LIMIT 1);
	
	SET vPCT =(SELECT 
     IFNULL(ROUND((((BPP2.BPP_VALOR3 + BPP3.BPP_VALOR3) / (CASE BPP4.BPP_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPP4.BPP_VALOR3
                    END)) * 100),
                    2),
            2) AS PCT
FROM
    BVSP_BPP BPP1
        INNER JOIN
    BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
WHERE
    BPP1.ID_EMPRESA = vID_EMPRESA
        AND BPP2.BPP_CONTA_CONTABIL = '2.01'
        AND BPP3.BPP_CONTA_CONTABIL = '2.02'
        AND BPP4.BPP_CONTA_CONTABIL = '2.03'
LIMIT 1);
	
	SET vPME =(SELECT 
     ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE (DRE.DRE_VALOR3 * - 1)
                        WHEN 0 THEN 1
                        ELSE (DRE.DRE_VALOR3 * - 1)
                    END)) * 360),
                    0),
            2) AS PME
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
LIMIT 1);
	
	SET vPMP =(SELECT 
     ROUND(IFNULL(((BPP.BPP_VALOR3 / ((CASE (DRE.DRE_VALOR3 * - 1)
                        WHEN 0 THEN 1
                        ELSE (DRE.DRE_VALOR3 * - 1)
                    END) + (BPA.BPA_VALOR3 - BPA.BPA_VALOR2))) * 360),
                    0),
            2) AS PMP
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN
    BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
LIMIT 1);
	
	SET vPMR =(SELECT 
     ROUND(IFNULL(((BPA.BPA_VALOR3 / (CASE DRE.DRE_VALOR3
                        WHEN 0 THEN 1
                        ELSE DRE.DRE_VALOR3
                    END)) * 360),
                    0),
            2) AS PMR
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
LIMIT 1);
	
	SET vRA = (SELECT 
    ROUND(IFNULL((DRE.DRE_VALOR3 / (CASE BPA.BPA_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPA.BPA_VALOR3
                    END)) * 100,
                    0),
            2) AS RA
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPA.BPA_CONTA_CONTABIL = '1'
LIMIT 1);
	
	SET vRPL =(SELECT 
     ROUND(IFNULL((DRE.DRE_VALOR3 / (CASE BPP.BPP_VALOR3
                        WHEN 0 THEN 1
                        ELSE BPP.BPP_VALOR3
                    END)) * 100,
                    0),
            2) AS RPL
FROM
    BVSP_DRE DRE
        INNER JOIN
    BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
WHERE
    DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPP.BPP_CONTA_CONTABIL = '2.03'
LIMIT 1);
	
	
	##INSERE DADOS CALCULADOS NA TABELA:
	INSERT INTO BVSP_INDICADORES 
		  (ID_EMPRESA,
		   ANO,
		   IE_PCT,
		   IE_CE,
		   IE_IPL,
		   IL_LG,
		   IL_LC,
		   IL_LS,
		   IL_CCL,
		   IR_GA,
		   IR_ML,
		   IR_RA,
		   IR_RPL,
		   IA_PME,
		   IA_PMR,
		   IA_PMP,
		   IA_CO,
		   IA_CF) 
	 VALUES 
		  (vID_EMPRESA,
		   vANO3,
		   vPCT,
		   vCE,
		   vIPL,
		   vLG,
		   vLC,
		   vLS,
		   vCCL,
		   vGA,
		   vML,
		   vRA,
		   vRPL,
		   vPME,
		   vPMR,
		   vPMP,
		   vCO,
		   vCF);
    
END$$

DELIMITER ;

