--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Junho-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BVSP_BPA_DADOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPA_DADOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPA_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPA_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPA_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPA_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPA_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPA_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 901 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_DADOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_DADOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 941 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_BPP_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_BPP_SEQ4"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_DRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_DRE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_DRE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_DRE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 501 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_EMPRESA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_EMPRESA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_EMPRESAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_EMPRESAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_IND_ESTRUTURA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_IND_ESTRUTURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_INDICADORES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_INDICADORES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_INDICADORES_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_INDICADORES_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_INDICADORES_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_INDICADORES_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_INDICADORES_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_INDICADORES_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_ISF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_ISF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BVSP_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."BVSP_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAB_DRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."TAB_DRE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."TABLE1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAB_TESTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOVESPA"."TAB_TESTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 25961 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BVSP_BPA
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_BPA" 
   (	"ID_BPA" NUMBER(20,0), 
	"ID_EMPRESA" NUMBER(20,0), 
	"BPA_PERIODO1" VARCHAR2(40 BYTE), 
	"BPA_CONTA_CONTABIL" VARCHAR2(1000 BYTE), 
	"BPA_DESCRICAO" VARCHAR2(1000 BYTE), 
	"BPA_VALOR1" FLOAT(20), 
	"BPA_PERIODO2" VARCHAR2(40 BYTE), 
	"BPA_VALOR2" FLOAT(20), 
	"BPA_PERIODO3" VARCHAR2(40 BYTE), 
	"BPA_VALOR3" FLOAT(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BVSP_BPP
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_BPP" 
   (	"ID_BPP" NUMBER(20,0), 
	"ID_EMPRESA" NUMBER(20,0), 
	"BPP_PERIODO1" VARCHAR2(40 BYTE), 
	"BPP_CONTA_CONTABIL" VARCHAR2(1000 BYTE), 
	"BPP_DESCRICAO" VARCHAR2(1000 BYTE), 
	"BPP_VALOR1" FLOAT(20), 
	"BPP_VALOR2" FLOAT(20), 
	"BPP_VALOR3" FLOAT(20), 
	"BPP_PERIODO2" VARCHAR2(40 BYTE), 
	"BPP_PERIODO3" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BVSP_DRE
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_DRE" 
   (	"ID_DRE" NUMBER(20,0), 
	"ID_EMPRESA" NUMBER(20,0), 
	"DRE_PERIODO1" VARCHAR2(40 BYTE), 
	"DRE_CONTA_CONTABIL" VARCHAR2(1000 BYTE), 
	"DRE_DESCRICAO" VARCHAR2(1000 BYTE), 
	"DRE_VALOR1" FLOAT(20), 
	"DRE_VALOR2" FLOAT(20), 
	"DRE_VALOR3" FLOAT(20), 
	"DRE_PERIODO2" VARCHAR2(40 BYTE), 
	"DRE_PERIODO3" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BVSP_EMPRESA
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_EMPRESA" 
   (	"ID_EMPRESA" NUMBER(20,0), 
	"RAZAO_SOCIAL" VARCHAR2(50 BYTE), 
	"NOME_FANTASIA" VARCHAR2(50 BYTE), 
	"CNPJ" VARCHAR2(14 BYTE), 
	"ATIVIDADE" VARCHAR2(140 BYTE), 
	"DRE" CHAR(1 BYTE), 
	"BPA" CHAR(1 BYTE), 
	"BPP" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BVSP_INDICADORES
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_INDICADORES" 
   (	"ID_INDICADORES" NUMBER, 
	"ID_EMPRESA" NUMBER, 
	"ANO" NUMBER DEFAULT 1900, 
	"IE_PCT" NUMBER DEFAULT 0, 
	"IE_CE" NUMBER DEFAULT 0, 
	"IE_IPL" NUMBER DEFAULT 0, 
	"IL_LG" NUMBER DEFAULT 0, 
	"IL_LC" NUMBER DEFAULT 0, 
	"IL_LS" NUMBER DEFAULT 0, 
	"IL_CCL" NUMBER DEFAULT 0, 
	"IR_GA" NUMBER DEFAULT 0, 
	"IR_ML" NUMBER DEFAULT 0, 
	"IR_RA" NUMBER DEFAULT 0, 
	"IR_RPL" NUMBER DEFAULT 0, 
	"IA_PME" NUMBER DEFAULT 0, 
	"IA_PMR" NUMBER DEFAULT 0, 
	"IA_PMP" NUMBER DEFAULT 0, 
	"IA_CO" NUMBER DEFAULT 0, 
	"IA_CF" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BVSP_USUARIO
--------------------------------------------------------

  CREATE TABLE "BOVESPA"."BVSP_USUARIO" 
   (	"ID_USUARIO" NUMBER(20,0), 
	"USUARIO" VARCHAR2(40 BYTE), 
	"NOME_COMPLETO" VARCHAR2(60 BYTE), 
	"SENHA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BOVESPA.BVSP_BPA
SET DEFINE OFF;
REM INSERTING into BOVESPA.BVSP_BPP
SET DEFINE OFF;
REM INSERTING into BOVESPA.BVSP_DRE
SET DEFINE OFF;
REM INSERTING into BOVESPA.BVSP_EMPRESA
SET DEFINE OFF;
Insert into BOVESPA.BVSP_EMPRESA (ID_EMPRESA,RAZAO_SOCIAL,NOME_FANTASIA,CNPJ,ATIVIDADE,DRE,BPA,BPP) values ('101','VALE SA','VALE SA','31313677000109','MINERAÇÃO',null,null,null);
Insert into BOVESPA.BVSP_EMPRESA (ID_EMPRESA,RAZAO_SOCIAL,NOME_FANTASIA,CNPJ,ATIVIDADE,DRE,BPA,BPP) values ('65','AMBEV SA','AMBEV SA','84313884000124','BEBIDAS',null,null,null);
REM INSERTING into BOVESPA.BVSP_INDICADORES
SET DEFINE OFF;
REM INSERTING into BOVESPA.BVSP_USUARIO
SET DEFINE OFF;
Insert into BOVESPA.BVSP_USUARIO (ID_USUARIO,USUARIO,NOME_COMPLETO,SENHA) values ('1','ecardoso','Everaldo Cardoso de Araújo','12345');
Insert into BOVESPA.BVSP_USUARIO (ID_USUARIO,USUARIO,NOME_COMPLETO,SENHA) values ('2','rrufino','Rafael Pereira Rufino Leite','12345');
Insert into BOVESPA.BVSP_USUARIO (ID_USUARIO,USUARIO,NOME_COMPLETO,SENHA) values ('3','wjunior','Walter Júnior','12345');
Insert into BOVESPA.BVSP_USUARIO (ID_USUARIO,USUARIO,NOME_COMPLETO,SENHA) values ('4','bbrandao','Bruno Brandão','12345');
--------------------------------------------------------
--  DDL for Index BVSP_EMPRESAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOVESPA"."BVSP_EMPRESAS_PK" ON "BOVESPA"."BVSP_EMPRESA" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BVSP_IND_ESTRUTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOVESPA"."BVSP_IND_ESTRUTURA_PK" ON "BOVESPA"."BVSP_INDICADORES" ("ID_INDICADORES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BVSP_BPP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOVESPA"."BVSP_BPP_PK" ON "BOVESPA"."BVSP_BPP" ("ID_BPP", "ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BVSP_DRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOVESPA"."BVSP_DRE_PK" ON "BOVESPA"."BVSP_DRE" ("ID_DRE", "ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BVSP_BPA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOVESPA"."BVSP_BPA_PK" ON "BOVESPA"."BVSP_BPA" ("ID_BPA", "ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BVSP_USUARIO
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOVESPA"."BVSP_USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVSP_BPA
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_BPA" ADD CONSTRAINT "BVSP_BPA_PK" PRIMARY KEY ("ID_BPA", "ID_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOVESPA"."BVSP_BPA" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_BPA" MODIFY ("ID_BPA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVSP_DRE
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_DRE" ADD CONSTRAINT "BVSP_DRE_PK" PRIMARY KEY ("ID_DRE", "ID_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOVESPA"."BVSP_DRE" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_DRE" MODIFY ("ID_DRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVSP_BPP
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_BPP" ADD CONSTRAINT "BVSP_BPP_PK" PRIMARY KEY ("ID_BPP", "ID_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOVESPA"."BVSP_BPP" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_BPP" MODIFY ("ID_BPP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVSP_INDICADORES
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IA_CF" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IA_CO" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IA_PMP" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IA_PMR" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IA_PME" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IR_RPL" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IR_RA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IR_ML" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IR_GA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IL_CCL" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IL_LS" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IL_LC" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IL_LG" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IE_IPL" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IE_CE" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("IE_PCT" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("ANO" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" MODIFY ("ID_INDICADORES" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" ADD CONSTRAINT "BVSP_IND_ESTRUTURA_PK" PRIMARY KEY ("ID_INDICADORES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BVSP_EMPRESA
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" ADD CONSTRAINT "BVSP_EMPRESAS_PK" PRIMARY KEY ("ID_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" MODIFY ("ATIVIDADE" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" MODIFY ("CNPJ" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" MODIFY ("NOME_FANTASIA" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" MODIFY ("RAZAO_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "BOVESPA"."BVSP_EMPRESA" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BVSP_BPA
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_BPA" ADD CONSTRAINT "BVSP_BPA_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "BOVESPA"."BVSP_EMPRESA" ("ID_EMPRESA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVSP_BPP
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_BPP" ADD CONSTRAINT "BVSP_BPP_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "BOVESPA"."BVSP_EMPRESA" ("ID_EMPRESA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVSP_DRE
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_DRE" ADD CONSTRAINT "BVSP_DRE_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "BOVESPA"."BVSP_EMPRESA" ("ID_EMPRESA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVSP_INDICADORES
--------------------------------------------------------

  ALTER TABLE "BOVESPA"."BVSP_INDICADORES" ADD CONSTRAINT "BVSP_INDICADORES_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "BOVESPA"."BVSP_EMPRESA" ("ID_EMPRESA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_BPA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_BPA_TRG" 
BEFORE INSERT ON BVSP_BPA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_BPA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_BPA_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_BPA_TRG1" 
BEFORE INSERT ON BVSP_BPA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_BPA IS NULL THEN
      SELECT BVSP_BPA_SEQ3.NEXTVAL INTO :NEW.ID_BPA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_BPA_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_BPP_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_BPP_TRG" 
BEFORE INSERT ON BVSP_BPP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_BPP_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_BPP_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_BPP_TRG1" 
BEFORE INSERT ON BVSP_BPP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_BPP_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_BPP_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_BPP_TRG2" 
BEFORE INSERT ON BVSP_BPP 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_BPP IS NULL THEN
      SELECT BVSP_BPP_SEQ4.NEXTVAL INTO :NEW.ID_BPP FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_BPP_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_DRE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_DRE_TRG" 
BEFORE INSERT ON BVSP_DRE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DRE IS NULL THEN
      SELECT BVSP_DRE_SEQ1.NEXTVAL INTO :NEW.ID_DRE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_DRE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_EMPRESAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_EMPRESAS_TRG" 
BEFORE INSERT ON BVSP_EMPRESA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_EMPRESAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_EMPRESA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_EMPRESA_TRG" 
BEFORE INSERT ON BVSP_EMPRESA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPRESA IS NULL THEN
      SELECT BVSP_EMPRESA_SEQ.NEXTVAL INTO :NEW.ID_EMPRESA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_EMPRESA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_INDICADORES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_INDICADORES_TRG" 
BEFORE INSERT ON BVSP_INDICADORES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_INDICADORES IS NULL THEN
      SELECT BVSP_INDICADORES_SEQ3.NEXTVAL INTO :NEW.ID_INDICADORES FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_INDICADORES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BVSP_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BOVESPA"."BVSP_USUARIO_TRG" 
BEFORE INSERT ON BVSP_USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_USUARIO IS NULL THEN
      SELECT BVSP_USUARIO_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BOVESPA"."BVSP_USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure BVSP_SP_INDICADORES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "BOVESPA"."BVSP_SP_INDICADORES" (
  vID_EMPRESA INTEGER,
  vANO1 VARCHAR,
  vANO2 VARCHAR,
  vANO3 VARCHAR
)
IS
  vCCL REAL := 0;
  vCE REAL := 0;
  vCF REAL:= 0;
  vCO REAL:= 0;
  vGA REAL:= 0;
  vIPL REAL:= 0;
  vLC REAL:= 0;
  vLG REAL:= 0;
  vLS REAL:= 0;
  vML REAL:= 0;
  vPCT REAL:= 0;
  vPME REAL:= 0;
  vPMP REAL:= 0;
  vPMR REAL:= 0;
  vRA REAL:= 0;
  vRPL REAL:= 0;
BEGIN
        DELETE FROM BVSP_INDICADORES
        WHERE BVSP_INDICADORES.ID_EMPRESA = vID_EMPRESA;
        
        --#########ANO 1#########--
        
        --CCL:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR1 - BVSP_BPP.BPP_VALOR1,0),2) AS CCL INTO vCCL
        FROM BVSP_BPP
        INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
        
        --CE:
        SELECT 
             NVL(TRUNC((BPP1.BPP_VALOR1/
             (CASE (BPP1.BPP_VALOR1+BPP2.BPP_VALOR1) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR1+BPP2.BPP_VALOR1) END)
             * 100),2),0) AS CE INTO vCE
        FROM BVSP_BPP
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;   
        
        --CF:
        SELECT
            (SELECT 
              TRUNC(NVL(((BPP.BPP_VALOR1/
              ((CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END) 
               + (BPA.BPA_VALOR1 - 0))) * 360),0),2) AS PMP
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.02'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
            AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
            AND ROWNUM < 2)
            -
            ((SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR1/
                (CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
                ) * 360),0),2) AS PME
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.02'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
              AND ROWNUM < 2)
              +
              (SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR1/
                (CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
                ) * 360),0),2) AS PMR
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.01'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
              AND ROWNUM < 2)
            ) AS CF INTO vCF
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        --CO:
        SELECT
            TRUNC(NVL(
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR1/
              (CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.02'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
            AND ROWNUM < 2)
          +
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR1/
              (CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.01'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
            AND ROWNUM < 2)
            ,0),2) AS CO INTO vCO
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        
        --GA:
        SELECT 
            TRUNC(NVL(DRE.DRE_VALOR1/
            (CASE BPA.BPA_VALOR1 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR2 END) 
            ,0),2) AS GA INTO vGA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --IPL:
        SELECT 
             NVL(TRUNC((((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) /
             (CASE BPP1.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR1 END)
             ) * 100),2),0)  AS IPL INTO vIPL
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
        AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
        AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
        AND BPP1.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --LC:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR1 / 
            (CASE BVSP_BPP.BPP_VALOR1 WHEN 0 THEN 1 ELSE BVSP_BPP.BPP_VALOR1 END)
            ,0),2) AS LC INTO vLC
        FROM BVSP_BPA
        INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND ROWNUM < 2;

        --LG:
        SELECT
            TRUNC(NVL(BPA.BPA_VALOR1/
            (CASE (BPP1.BPP_VALOR1 + BPP2.BPP_VALOR1) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR1 + BPP2.BPP_VALOR1) END)
            ,0),2) AS LG INTO vLG
        FROM BVSP_BPA BPA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
        WHERE BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;
        
        --LS:
        SELECT 
           TRUNC(NVL(((BPA1.BPA_VALOR1 + BPA2.BPA_VALOR1 + BPA3.BPA_VALOR1) / 
           (CASE BPP1.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR1 END)
           ),0),2) AS LS INTO vLS
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
        AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
        AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
      
        --ML:
        SELECT 
          TRUNC(NVL(((DRE.DRE_VALOR1/
          (CASE DRE1.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE1.DRE_VALOR1 END)
          ) * 100),0),2) AS ML INTO vML
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND DRE1.DRE_CONTA_CONTABIL = '3.01'
        AND ROWNUM < 2;
        
        --PCT:
        SELECT 
              NVL(TRUNC((((BPP2.BPP_VALOR1 + BPP3.BPP_VALOR1) / 
              (CASE BPP4.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP4.BPP_VALOR1 END)
              ) * 100),2),2) AS PCT INTO vPCT
        FROM BVSP_BPP BPP1
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
        WHERE BPP1.ID_EMPRESA = vID_EMPRESA
        AND BPP2.BPP_CONTA_CONTABIL = '2.01'
        AND BPP3.BPP_CONTA_CONTABIL = '2.02'
        AND BPP4.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --PME:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR1/
          (CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
          ) * 360),0),2) AS PME INTO vPME
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND ROWNUM < 2;
        
        --PMP:
         SELECT 
          TRUNC(NVL(((BPP.BPP_VALOR1/
          ((CASE (DRE.DRE_VALOR1 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR1 * -1) END)
           + (BPA.BPA_VALOR1 - 0))) * 360),0),2) AS PMP INTO vPMP
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
        AND ROWNUM < 2;
        
        --PMR:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR1/
          (CASE DRE.DRE_VALOR1 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR1 END)
          ) * 360),0),2) AS PMR INTO vPMR
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
        AND ROWNUM < 2;
        
        --RA:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR1/
          (CASE BPA.BPA_VALOR1 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR1 END)
          ) * 100,0),2) AS RA INTO vRA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --RPL:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR1/
          (CASE BPP.BPP_VALOR1 WHEN 0 THEN 1 ELSE BPP.BPP_VALOR1 END)
          ) * 100,0),2) AS RPL INTO vRPL
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPP.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        
        --INSERE DADOS CALCULADOS NA TABELA:
        INSERT INTO BVSP_INDICADORES 
              (ID_INDICADORES,
               ID_EMPRESA,
               ANO,
               IE_PCT,
               IE_CE,
               IE_IPL,
               IL_LG,
               IL_LC,
               IL_LS,
               IL_CCL,
               IR_GA,
               IR_ML,
               IR_RA,
               IR_RPL,
               IA_PME,
               IA_PMR,
               IA_PMP,
               IA_CO,
               IA_CF) 
         VALUES 
              (BVSP_INDICADORES_SEQ3.NEXTVAL,
               vID_EMPRESA,
               vANO1,
               vPCT,
               vCE,
               vIPL,
               vLG,
               vLC,
               vLS,
               vCCL,
               vGA,
               vML,
               vRA,
               vRPL,
               vPME,
               vPMR,
               vPMP,
               vCO,
               vCF);
               
               
               
        --#########ANO 2#########--
        --CCL:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR2 - BVSP_BPP.BPP_VALOR2,0),2) AS CCL INTO vCCL
        FROM BVSP_BPP
        INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
        
        --CE:
        SELECT 
             NVL(TRUNC((BPP1.BPP_VALOR2/
             (CASE (BPP1.BPP_VALOR2+BPP2.BPP_VALOR2) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR2+BPP2.BPP_VALOR2) END)
             * 100),2),0) AS CE INTO vCE
        FROM BVSP_BPP
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;   
        
        --CF:
        SELECT
            (SELECT 
                TRUNC(NVL(((BPP.BPP_VALOR2/
                ((CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
                 + (BPA.BPA_VALOR2 - BPA.BPA_VALOR1))) * 360),0),2) AS PMP 
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = vID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.02'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
              AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
              AND ROWNUM < 2)
            
            -
            ((SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR2/
                (CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
                ) * 360),0),2) AS PME
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.02'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
              AND ROWNUM < 2)
              +
              (SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR2/
                (CASE DRE.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR2 END)
                ) * 360),0),2) AS PMR
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.01'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
              AND ROWNUM < 2)
            ) AS CF INTO vCF
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        --CO:
        SELECT
            TRUNC(NVL(
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR2/
              (CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.02'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
            AND ROWNUM < 2)
          +
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR2/
              (CASE DRE.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR2 END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.01'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
            AND ROWNUM < 2)
            ,0),2) AS CO INTO vCO
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        
        --GA:
        SELECT 
            TRUNC(NVL(DRE.DRE_VALOR2/
            (CASE BPA.BPA_VALOR2 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR2 END) 
            ,0),2) AS GA INTO vGA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --IPL:
        SELECT 
             NVL(TRUNC((((BPA1.BPA_VALOR2 + BPA2.BPA_VALOR2 + BPA3.BPA_VALOR2) /
             (CASE BPP1.BPP_VALOR2 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR2 END)
             ) * 100),2),0)  AS IPL INTO vIPL
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
        AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
        AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
        AND BPP1.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --LC:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR2 / 
            (CASE BVSP_BPP.BPP_VALOR2 WHEN 0 THEN 1 ELSE BVSP_BPP.BPP_VALOR2 END)
            ,0),2) AS LC INTO vLC
        FROM BVSP_BPA
        INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND ROWNUM < 2;

        --LG:
        SELECT
            TRUNC(NVL(BPA.BPA_VALOR2/
            (CASE (BPP1.BPP_VALOR2 + BPP2.BPP_VALOR2) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR2 + BPP2.BPP_VALOR2) END)
            ,0),2) AS LG INTO vLG
        FROM BVSP_BPA BPA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
        WHERE BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;
        
        --LS:
        SELECT 
           TRUNC(NVL(((BPA1.BPA_VALOR2 + BPA2.BPA_VALOR2 + BPA3.BPA_VALOR2) / 
           (CASE BPP1.BPP_VALOR2 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR2 END)
           ),0),2) AS LS INTO vLS
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
        AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
        AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
      
        --ML:
        SELECT 
          TRUNC(NVL(((DRE.DRE_VALOR2/
          (CASE DRE1.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE1.DRE_VALOR2 END)
          ) * 100),0),2) AS ML INTO vML
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND DRE1.DRE_CONTA_CONTABIL = '3.01'
        AND ROWNUM < 2;
        
        --PCT:
        SELECT 
              NVL(TRUNC((((BPP2.BPP_VALOR2 + BPP3.BPP_VALOR2) / 
              (CASE BPP4.BPP_VALOR2 WHEN 0 THEN 1 ELSE BPP4.BPP_VALOR2 END)
              ) * 100),2),2) AS PCT INTO vPCT
        FROM BVSP_BPP BPP1
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
        WHERE BPP1.ID_EMPRESA = vID_EMPRESA
        AND BPP2.BPP_CONTA_CONTABIL = '2.01'
        AND BPP3.BPP_CONTA_CONTABIL = '2.02'
        AND BPP4.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --PME:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR2/
          (CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
          ) * 360),0),2) AS PME INTO vPME
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND ROWNUM < 2;
        
        --PMP:
         SELECT 
          TRUNC(NVL(((BPP.BPP_VALOR2/
          ((CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
           + (BPA.BPA_VALOR2 - BPA.BPA_VALOR1))) * 360),0),2) AS PMP INTO vPMP
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
        AND ROWNUM < 2;
        
        SELECT 
          TRUNC(NVL(((BPP.BPP_VALOR2/
          ((CASE (DRE.DRE_VALOR2 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR2 * -1) END)
           + (BPA.BPA_VALOR2 - BPA.BPA_VALOR3))) * 360),0),2) AS PMP INTO vPMP
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
        AND ROWNUM < 2;
        
        --PMR:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR2/
          (CASE DRE.DRE_VALOR2 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR2 END)
          ) * 360),0),2) AS PMR INTO vPMR
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
        AND ROWNUM < 2;
        
        --RA:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR2/
          (CASE BPA.BPA_VALOR2 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR2 END)
          ) * 100,0),2) AS RA INTO vRA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --RPL:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR2/
          (CASE BPP.BPP_VALOR2 WHEN 0 THEN 1 ELSE BPP.BPP_VALOR2 END)
          ) * 100,0),2) AS RPL INTO vRPL
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPP.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        
        --INSERE DADOS CALCULADOS NA TABELA:
        INSERT INTO BVSP_INDICADORES 
              (ID_INDICADORES,
               ID_EMPRESA,
               ANO,
               IE_PCT,
               IE_CE,
               IE_IPL,
               IL_LG,
               IL_LC,
               IL_LS,
               IL_CCL,
               IR_GA,
               IR_ML,
               IR_RA,
               IR_RPL,
               IA_PME,
               IA_PMR,
               IA_PMP,
               IA_CO,
               IA_CF) 
         VALUES 
              (BVSP_INDICADORES_SEQ3.NEXTVAL,
               vID_EMPRESA,
               vANO2,
               vPCT,
               vCE,
               vIPL,
               vLG,
               vLC,
               vLS,
               vCCL,
               vGA,
               vML,
               vRA,
               vRPL,
               vPME,
               vPMR,
               vPMP,
               vCO,
               vCF);
               
               
      --#########ANO 3#########--
        --CCL:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR3 - BVSP_BPP.BPP_VALOR3,0),2) AS CCL INTO vCCL
        FROM BVSP_BPP
        INNER JOIN BVSP_BPA ON BVSP_BPA.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
        
        --CE:
        SELECT 
             NVL(TRUNC((BPP1.BPP_VALOR3/
             (CASE (BPP1.BPP_VALOR3+BPP2.BPP_VALOR3) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR3+BPP2.BPP_VALOR3) END)
             * 100),2),0) AS CE INTO vCE
        FROM BVSP_BPP
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BVSP_BPP.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;   
        
        --CF:
        SELECT
            (SELECT 
              TRUNC(NVL(((BPP.BPP_VALOR3/
              ((CASE (DRE.DRE_VALOR3 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR3 * -1) END)
               + (BPA.BPA_VALOR3 - BPA.BPA_VALOR2))) * 360),0),2) AS PMP
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.02'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
            AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
            AND ROWNUM < 2)
            -
            ((SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR3/
                (CASE (DRE.DRE_VALOR3 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR3 * -1) END)
                ) * 360),0),2) AS PME
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.02'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
              AND ROWNUM < 2)
              +
              (SELECT 
                TRUNC(NVL(((BPA.BPA_VALOR3/
                (CASE DRE.DRE_VALOR3 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR3 END)
                ) * 360),0),2) AS PMR
              FROM BVSP_DRE DRE
              INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
              WHERE DRE.ID_EMPRESA = BVSP_DRE.ID_EMPRESA
              AND DRE.DRE_CONTA_CONTABIL = '3.01'
              AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
              AND ROWNUM < 2)
            ) AS CF INTO vCF
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        --CO:
        SELECT
            TRUNC(NVL(
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR3/
              (CASE (DRE.DRE_VALOR3 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR3 * -1) END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.02'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
            AND ROWNUM < 2)
          +
            (SELECT 
              TRUNC(NVL(((BPA.BPA_VALOR3/
              (CASE DRE.DRE_VALOR3 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR3 END)
              ) * 360),0),2)
            FROM BVSP_DRE DRE
            INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
            WHERE DRE.ID_EMPRESA = vID_EMPRESA
            AND DRE.DRE_CONTA_CONTABIL = '3.01'
            AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
            AND ROWNUM < 2)
            ,0),2) AS CO INTO vCO
        FROM BVSP_DRE
        WHERE BVSP_DRE.ID_EMPRESA = vID_EMPRESA
        AND ROWNUM < 2;
        
        
        --GA:
        SELECT 
            TRUNC(NVL(DRE.DRE_VALOR3/
            (CASE BPA.BPA_VALOR3 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR3 END) 
            ,0),2) AS GA INTO vGA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --IPL:
        SELECT 
             NVL(TRUNC((((BPA1.BPA_VALOR3 + BPA2.BPA_VALOR3 + BPA3.BPA_VALOR3) /
             (CASE BPP1.BPP_VALOR3 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR3 END)
             ) * 100),2),0)  AS IPL INTO vIPL
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.02.02'
        AND BPA2.BPA_CONTA_CONTABIL = '1.02.03'
        AND BPA3.BPA_CONTA_CONTABIL = '1.02.04'
        AND BPP1.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --LC:
        SELECT 
            TRUNC(NVL(BVSP_BPA.BPA_VALOR3 / 
            (CASE BVSP_BPP.BPP_VALOR3 WHEN 0 THEN 1 ELSE BVSP_BPP.BPP_VALOR3 END)
            ,0),2) AS LC INTO vLC
        FROM BVSP_BPA
        INNER JOIN BVSP_BPP ON BVSP_BPP.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPP.ID_EMPRESA = vID_EMPRESA
        AND BVSP_BPP.BPP_CONTA_CONTABIL = '2.01'
        AND BVSP_BPA.BPA_CONTA_CONTABIL = '1.01'
        AND ROWNUM < 2;

        --LG:
        SELECT
            TRUNC(NVL(BPA.BPA_VALOR3/
            (CASE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3) WHEN 0 THEN 1 ELSE (BPP1.BPP_VALOR3 + BPP2.BPP_VALOR3) END)
            ,0),2) AS LG INTO vLG
        FROM BVSP_BPA BPA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPA.ID_EMPRESA
        WHERE BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA.BPA_CONTA_CONTABIL = '1.02.01'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND BPP2.BPP_CONTA_CONTABIL = '2.02'
        AND ROWNUM < 2;
        
        --LS:
        SELECT 
           TRUNC(NVL(((BPA1.BPA_VALOR3 + BPA2.BPA_VALOR3 + BPA3.BPA_VALOR3) / 
           (CASE BPP1.BPP_VALOR3 WHEN 0 THEN 1 ELSE BPP1.BPP_VALOR3 END)
           ),0),2) AS LS INTO vLS
        FROM BVSP_BPA
        INNER JOIN BVSP_BPA BPA1 ON BPA1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA2 ON BPA2.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPA BPA3 ON BPA3.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP1 ON BPP1.ID_EMPRESA = BVSP_BPA.ID_EMPRESA
        WHERE BVSP_BPA.ID_EMPRESA = vID_EMPRESA
        AND BPA1.BPA_CONTA_CONTABIL = '1.01.01'
        AND BPA2.BPA_CONTA_CONTABIL = '1.01.02'
        AND BPA3.BPA_CONTA_CONTABIL = '1.01.03'
        AND BPP1.BPP_CONTA_CONTABIL = '2.01'
        AND ROWNUM < 2;
      
        --ML:
        SELECT 
          TRUNC(NVL(((DRE.DRE_VALOR3/
          (CASE DRE1.DRE_VALOR3 WHEN 0 THEN 1 ELSE DRE1.DRE_VALOR3 END)
          ) * 100),0),2) AS ML INTO vML
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_DRE DRE1 ON DRE1.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND DRE1.DRE_CONTA_CONTABIL = '3.01'
        AND ROWNUM < 2;
        
        --PCT:
        SELECT 
              NVL(TRUNC((((BPP2.BPP_VALOR3 + BPP3.BPP_VALOR3) / 
              (CASE BPP4.BPP_VALOR3 WHEN 0 THEN 1 ELSE BPP4.BPP_VALOR3 END)
              ) * 100),2),2) AS PCT INTO vPCT
        FROM BVSP_BPP BPP1
        INNER JOIN BVSP_BPP BPP2 ON BPP2.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP3 ON BPP3.ID_EMPRESA = BPP1.ID_EMPRESA
        INNER JOIN BVSP_BPP BPP4 ON BPP4.ID_EMPRESA = BPP1.ID_EMPRESA
        WHERE BPP1.ID_EMPRESA = vID_EMPRESA
        AND BPP2.BPP_CONTA_CONTABIL = '2.01'
        AND BPP3.BPP_CONTA_CONTABIL = '2.02'
        AND BPP4.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        --PME:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR3/
          (CASE (DRE.DRE_VALOR3 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR3 * -1) END)
          ) * 360),0),2) AS PME INTO vPME
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.02'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
        AND ROWNUM < 2;
        
        --PMP:
         SELECT 
            TRUNC(NVL(((BPP.BPP_VALOR3/
            ((CASE (DRE.DRE_VALOR3 * -1) WHEN 0 THEN 1 ELSE (DRE.DRE_VALOR3 * -1) END)
             + (BPA.BPA_VALOR3 - BPA.BPA_VALOR2))) * 360),0),2) AS PMP INTO vPMP
          FROM BVSP_DRE DRE
          INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
          INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
          WHERE DRE.ID_EMPRESA = vID_EMPRESA
          AND DRE.DRE_CONTA_CONTABIL = '3.02'
          AND BPA.BPA_CONTA_CONTABIL = '1.01.04'
          AND BPP.BPP_CONTA_CONTABIL = '2.01.02'
          AND ROWNUM < 2;
        
        --PMR:
        SELECT 
          TRUNC(NVL(((BPA.BPA_VALOR3/
          (CASE DRE.DRE_VALOR3 WHEN 0 THEN 1 ELSE DRE.DRE_VALOR3 END)
          ) * 360),0),2) AS PMR INTO vPMR
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.01'
        AND BPA.BPA_CONTA_CONTABIL = '1.01.03'
        AND ROWNUM < 2;
        
        --RA:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR3/
          (CASE BPA.BPA_VALOR3 WHEN 0 THEN 1 ELSE BPA.BPA_VALOR3 END)
          ) * 100,0),2) AS RA INTO vRA
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPA BPA ON BPA.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPA.BPA_CONTA_CONTABIL = '1'
        AND ROWNUM < 2;
        
        --RPL:
        SELECT 
          TRUNC(NVL((DRE.DRE_VALOR3/
          (CASE BPP.BPP_VALOR3 WHEN 0 THEN 1 ELSE BPP.BPP_VALOR3 END)
          ) * 100,0),2) AS RPL INTO vRPL
        FROM BVSP_DRE DRE
        INNER JOIN BVSP_BPP BPP ON BPP.ID_EMPRESA = DRE.ID_EMPRESA
        WHERE DRE.ID_EMPRESA = vID_EMPRESA
        AND DRE.DRE_CONTA_CONTABIL = '3.09'
        AND BPP.BPP_CONTA_CONTABIL = '2.03'
        AND ROWNUM < 2;
        
        
        --INSERE DADOS CALCULADOS NA TABELA:
        INSERT INTO BVSP_INDICADORES 
              (ID_INDICADORES,
               ID_EMPRESA,
               ANO,
               IE_PCT,
               IE_CE,
               IE_IPL,
               IL_LG,
               IL_LC,
               IL_LS,
               IL_CCL,
               IR_GA,
               IR_ML,
               IR_RA,
               IR_RPL,
               IA_PME,
               IA_PMR,
               IA_PMP,
               IA_CO,
               IA_CF) 
         VALUES 
              (BVSP_INDICADORES_SEQ3.NEXTVAL,
               vID_EMPRESA,
               vANO3,
               vPCT,
               vCE,
               vIPL,
               vLG,
               vLC,
               vLS,
               vCCL,
               vGA,
               vML,
               vRA,
               vRPL,
               vPME,
               vPMR,
               vPMP,
               vCO,
               vCF);
        
  
END BVSP_SP_INDICADORES;

/
