package Visao;

import static App.AppFinanceiro.abrirVisao;
import static App.AppFinanceiro.conn;
import Dados.DadosManipulacao;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author E. Cardoso de Araújo
 */
public class VisaoInicio extends javax.swing.JFrame {

    /**
     * Creates new form VisaoInicio
     */
    public VisaoInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        pnlInicio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        txtDados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDados = new javax.swing.JMenu();
        mnuCadEmpresas = new javax.swing.JMenuItem();
        mnuImportar = new javax.swing.JMenuItem();
        mnuAcoes = new javax.swing.JMenu();
        mnuTrocarUsuario = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bovespa Analytics");

        pnlInicio.setBackground(new java.awt.Color(51, 51, 51));
        pnlInicio.setForeground(new java.awt.Color(102, 102, 102));
        pnlInicio.setToolTipText("");
        pnlInicio.setAutoscrolls(true);

        jToolBar1.setRollover(true);

        txtDados.setEditable(false);
        jToolBar1.add(txtDados);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/logo.png"))); // NOI18N

        pnlInicio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlInicio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnuDados.setText("Dados");

        mnuCadEmpresas.setText("Cadastrar empresas");
        mnuCadEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEmpresasActionPerformed(evt);
            }
        });
        mnuDados.add(mnuCadEmpresas);

        mnuImportar.setText("Importar dados");
        mnuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportarActionPerformed(evt);
            }
        });
        mnuDados.add(mnuImportar);

        jMenuBar1.add(mnuDados);

        mnuAcoes.setText("Ações");
        mnuAcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcoesActionPerformed(evt);
            }
        });

        mnuTrocarUsuario.setText("Trocar usuário");
        mnuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrocarUsuarioActionPerformed(evt);
            }
        });
        mnuAcoes.add(mnuTrocarUsuario);

        mnuSair.setText("Fechar");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuAcoes.add(mnuSair);

        jMenuBar1.add(mnuAcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInicio)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAcoesActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        try{
            this.dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), this.getTitle(),0);
        }
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportarActionPerformed
        try{
            abrirVisao(pnlInicio,new VisaoImpExp());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), this.getTitle(),0);
        }
    }//GEN-LAST:event_mnuImportarActionPerformed

    private void mnuCadEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadEmpresasActionPerformed
        try {
            abrirVisao(pnlInicio,new VisaoEmpresa());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), this.getTitle(),0);
        }
    }//GEN-LAST:event_mnuCadEmpresasActionPerformed

    private void mnuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrocarUsuarioActionPerformed
        try {
            this.trocarUsuario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace(), this.getTitle(),0);
        }
    }//GEN-LAST:event_mnuTrocarUsuarioActionPerformed

    private void trocarUsuario(){
        try{
            this.pnlInicio.removeAll();
            this.pnlInicio.repaint();
            new VisaoAutenticacao().setVisible(true);
            this.dispose();
        }catch(Exception ex){
            throw ex;
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    public javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuAcoes;
    private javax.swing.JMenuItem mnuCadEmpresas;
    private javax.swing.JMenu mnuDados;
    private javax.swing.JMenuItem mnuImportar;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuTrocarUsuario;
    public javax.swing.JDesktopPane pnlInicio;
    public javax.swing.JTextField txtDados;
    // End of variables declaration//GEN-END:variables
}
